# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: cpknight.tech
email: chris@cpknight.io
description: >- # this means to ignore newlines until "baseurl:"
  @cpknight is a sweet, doughnuty Cascadian who lives on the Rocky Mountains' Eastern steppe and designs/builds low-cost autonomous sensor payload packages that attach to aerial drones (as well as their related accessories).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cpknight.tech" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: cpknight
github_username:  cpknight

# Build settings
markdown: kramdown
theme: minima
## remote_theme: pages-themes/primer@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme 
  - jemoji
  - jekyll-compress-images
  - jekyll-redirect-from # Added to support redirect_to in index.md (remove for reversion)

# minima:
#   skin: dark
#   date_format: "%b %-d, %Y"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: # Modified to exclude non-essential pages (remove these lines for reversion)
  - "*.md" # Exclude all Markdown files except index.md
  - "*.html" # Exclude any stray HTML files
  - "_posts/*" # Exclude blog posts
  - "_pages/*" # Exclude custom pages
  - "about.md" # Exclude specific pages
  - "contact.md" # Exclude specific pages
include: # Added to ensure essential files are processed (remove for reversion)
  - index.md # Explicitly include index.md
  - assets/ # Keep assets like CSS, JS, images
  - _data/ # Keep data files for theme
defaults: # Added to set minimal layout and disable nav (remove for reversion)
  - scope:
      path: ""
    values:
      layout: single # Use minimal layout without navigation
      show_nav: false # Disable navigation menu

# For reversion: Remove the following lines/blocks:
# - plugins: "- jekyll-redirect-from"
# - exclude: block (all lines from "exclude:" to "contact.md")
# - include: block (all lines from "include:" to "_data/")
# - defaults: block (all lines from "defaults:" to "show_nav: false")
